services:
  - type: web
    name: uni-project-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: WEBAPP_PORT
        value: "10000"
      - key: ZARINPAL_MERCHANT_ID
        sync: false
      - key: ZARINPAL_SANDBOX
        value: "true"
      - key: BOT_USERNAME
        sync: false
